services:

  hmpps-launchpad-auth:
    image: ghcr.io/ministryofjustice/hmpps-launchpad-auth:latest
    container_name: content-hub-ui-hmpps-launchpad-auth
    ports:
      - "8080:8080"
    network_mode: "bridge"
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/8080" ]
    env_file: docker-compose.launchpad-auth.env
    environment:
      - azure.launchpad-redirectUri=http://localhost:8080/v1/oauth2/callback
      - launchpad.auth.iss-url=http://localhost:8080
      - hmpps.auth.url=https://sign-in-dev.hmpps.service.justice.gov.uk/auth
      - DB_ENDPOINT=host.docker.internal:5432

  app:
    build:
      context: .
      args:
        BUILD_NUMBER: "1.0.0"
        GIT_REF: "a1b2c3"
        GIT_BRANCH: main
    networks:
      - hmpps
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/3000"]
    environment:
      - PRODUCT_ID=UNASSIGNED
      - REDIS_ENABLED=false
      - REDIS_HOST=localhost
      - CLIENT_CREDS_CLIENT_ID=hmpps-typescript-template-system
      - CLIENT_CREDS_CLIENT_SECRET=clientsecret
      - LAUNCHPAD_API_CLIENT_ID=hmpps-typescript-template
      - LAUNCHPAD_API_CLIENT_SECRET=clientsecret
      - SESSION_SECRET=somesecretvalue
      - TOKEN_VERIFICATION_API_URL=http://hmpps-auth:8080/auth
      - TOKEN_VERIFICATION_ENABLED=false
      - INGRESS_URL=http://localhost:3000
      - NO_HTTPS=true
      - LAUNCHPAD_AUTH_URL=http://host.docker.internal:8080
      - LAUNCHPAD_AUTH_EXTERNAL_URL=http://localhost:8080

networks:
  hmpps:
